/**
 * Standardized error codes for consistent frontend error handling
 * Format: ERR_CATEGORY_SPECIFIC
 */
export const ERROR_CODES = {
  // Authentication (AUTH_*)
  AUTH_INVALID_CREDENTIALS: "ERR_AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_DEACTIVATED: "ERR_AUTH_ACCOUNT_DEACTIVATED",
  AUTH_TOKEN_MISSING: "ERR_AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "ERR_AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "ERR_AUTH_TOKEN_EXPIRED",

  // Authorization (AUTHZ_*)
  AUTHZ_INSUFFICIENT_ROLE: "ERR_AUTHZ_INSUFFICIENT_ROLE",
  AUTHZ_INSUFFICIENT_CLEARANCE: "ERR_AUTHZ_INSUFFICIENT_CLEARANCE",
  AUTHZ_INSUFFICIENT_RANK: "ERR_AUTHZ_INSUFFICIENT_RANK",

  // Validation (VAL_*)
  VAL_INVALID_PAYLOAD: "ERR_VAL_INVALID_PAYLOAD",
  VAL_FIELD_REQUIRED: "ERR_VAL_FIELD_REQUIRED",
  VAL_FIELD_INVALID_FORMAT: "ERR_VAL_FIELD_INVALID_FORMAT",
  VAL_DUPLICATE_RESOURCE: "ERR_VAL_DUPLICATE_RESOURCE",

  // Resource (RES_*)
  RES_NOT_FOUND: "ERR_RES_NOT_FOUND",
  RES_CREATE_FAILED: "ERR_RES_CREATE_FAILED",
  RES_UPDATE_FAILED: "ERR_RES_UPDATE_FAILED",
  RES_DELETE_FAILED: "ERR_RES_DELETE_FAILED",

  // Database (DB_*)
  DB_CONNECTION_FAILED: "ERR_DB_CONNECTION_FAILED",
  DB_QUERY_FAILED: "ERR_DB_QUERY_FAILED",

  // Server (SYS_*)
  SYS_INTERNAL_ERROR: "ERR_SYS_INTERNAL_ERROR",
  SYS_UNAVAILABLE: "ERR_SYS_UNAVAILABLE",
};
